spring.application.name=hexagonal

jrodrigues.client.address.url=http://localhost:8082/addresses

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=hexagonal
spring.mongodb.username=root
spring.mongodb.password=example
spring.mongodb.authentication-database=admin

server.port=8081